-- Lets the browser read the ClickPipes CDC replica (`oltp.pg_saved_sites` /
-- `oltp.pg_shortlists`, ADR-004) directly as the read-only `site` user, the same
-- browser-direct-to-Cloud pattern already used for `web.layers` / `web.assets`
-- (see 004_layers_schema.sql, 009_app_assets_schema.sql).
--
-- Unlike those tables, `oltp.*` is a DIFFERENT database from `web.*`, so the existing
-- wildcard `GRANT SELECT ON web.* TO site` (docs/architecture/clickhouse-as-webserver.md)
-- does NOT cover it — this table-level GRANT is the one piece of new access DDL this
-- feature needs.
--
-- This is a GRANT, not a CREATE USER / CREATE SETTINGS PROFILE — the family that
-- permanently wedged p_html / web_html / web_html2 when run during a version upgrade
-- (CLAUDE.md, "Traps that have already bitten us" #4). A GRANT is lower-risk, but the
-- same rule applies: confirm `SELECT version()` is stable across several probes (no
-- mid-upgrade state) before running this. Verified stable (26.4.1.2029 x3) on 2026-07-18.
--
-- Table-level, not column-scoped: every column on both tables is either already shown in
-- the panel (id, shortlist_id/city/business_type, label, lon, lat, h3_8, score, status,
-- created_at) or harmless PeerDB bookkeeping (_peerdb_synced_at/_peerdb_is_deleted/
-- _peerdb_version) that the read query itself filters on. Column-scoping would buy
-- nothing here.
--
-- Read pattern the grant exists for (FINAL dedups by id keeping the latest CDC version;
-- the is_deleted filter drops rows deleted in Postgres — see ADR-004 / CLAUDE.md):
--
--   SELECT ss.id, ss.shortlist_id, ss.label, ss.lon, ss.lat, ss.h3_8, ss.score, ss.status,
--          sl.city, sl.business_type, ss.created_at
--   FROM oltp.pg_saved_sites AS ss FINAL
--   JOIN oltp.pg_shortlists AS sl FINAL ON sl.id = ss.shortlist_id
--   WHERE ss.user_id = {user_id:String} AND ss.\_peerdb_is_deleted = 0
--     AND sl.\_peerdb_is_deleted = 0
--   ORDER BY ss.created_at DESC
--
-- Known limitation this GRANT does not fix (see report, not a permissions issue): the
-- ClickPipe was created with `allowNullableColumns: false`, so a Postgres NULL `score`
-- lands in ClickHouse as 0.0, not NULL — verified live with a canary NULL-score row.
-- `allowNullableColumns` is NOT PATCH-able on a running pipe (confirmed: PATCH echoes
-- back the old value unchanged, same "accepted but ignored" shape as the Postgres `size`
-- no-op). Fixing it for real means recreating the pipe. `provision.sh` now creates future
-- pipes with `allowNullableColumns: true`; the live pipe still collapses NULL to 0
-- because the app's only save path always sends a real numeric score today (never null),
-- this is latent, not an active data-correctness bug.

GRANT SELECT ON oltp.pg_saved_sites TO site;
GRANT SELECT ON oltp.pg_shortlists TO site;
